-module(data_skill).
-include("skill.hrl").
-export([ids/0,get/2]).

ids()->
	[1,2,3,11,12,13,14,15,21,22,23,24,25,31,32,33,34,35].

get(1,1)->
	{ok,#data_skill{
       id = 1,
       lv = 1,
		 name = <<"普通近战"/utf8>>,
		 swf = 0,
		 type = 0,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 0,
		 need_lv = 0,
		 need_mp = 0,
		 need_cast_time = 0,
		 cd = 500,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 0,
		 extra_att_rate = 1000,
		 buff_ids = [],
		 transfer = [],
		 explain = <<"普通近战"/utf8>>
}};
get(2,1)->
	{ok,#data_skill{
       id = 2,
       lv = 1,
		 name = <<"普通远战"/utf8>>,
		 swf = 0,
		 type = 0,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 0,
		 need_lv = 0,
		 need_mp = 0,
		 need_cast_time = 0,
		 cd = 500,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 0,
		 extra_att_rate = 1000,
		 buff_ids = [],
		 transfer = [],
		 explain = <<"普通远战"/utf8>>
}};
get(3,1)->
	{ok,#data_skill{
       id = 3,
       lv = 1,
		 name = <<"跳跃"/utf8>>,
		 swf = 0,
		 type = 2,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 0,
		 need_lv = 10,
		 need_mp = 1,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 2,
		 attack_range = 6,
		 extra_att = 0,
		 extra_att_rate = 0,
		 buff_ids = [],
		 transfer = [],
		 explain = <<"跳跃一段距离，每次消耗20点体力。（每10秒钟回复2点体力）"/utf8>>
}};
get(11,1)->
	{ok,#data_skill{
       id = 11,
       lv = 1,
		 name = <<"十字重斩"/utf8>>,
		 swf = 11,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 100,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 2,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 25,
		 extra_att_rate = 1050,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"（近身）对敌人造成105%的伤害，额外附加50点伤害"/utf8>>
}};
get(11,2)->
	{ok,#data_skill{
       id = 11,
       lv = 2,
		 name = <<"十字重斩"/utf8>>,
		 swf = 11,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 200,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 10,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 40,
		 extra_att_rate = 1060,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"（近身）对敌人造成105%的伤害，额外附加100点伤害"/utf8>>
}};
get(11,3)->
	{ok,#data_skill{
       id = 11,
       lv = 3,
		 name = <<"十字重斩"/utf8>>,
		 swf = 11,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 300,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 20,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 55,
		 extra_att_rate = 1070,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"（近身）对敌人造成105%的伤害，额外附加150点伤害"/utf8>>
}};
get(11,4)->
	{ok,#data_skill{
       id = 11,
       lv = 4,
		 name = <<"十字重斩"/utf8>>,
		 swf = 11,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 400,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 30,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 70,
		 extra_att_rate = 1080,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"（近身）对敌人造成105%的伤害，额外附加200点伤害"/utf8>>
}};
get(11,5)->
	{ok,#data_skill{
       id = 11,
       lv = 5,
		 name = <<"十字重斩"/utf8>>,
		 swf = 11,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 500,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 40,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 90,
		 extra_att_rate = 1090,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"（近身）对敌人造成105%的伤害，额外附加250点伤害"/utf8>>
}};
get(11,6)->
	{ok,#data_skill{
       id = 11,
       lv = 6,
		 name = <<"十字重斩"/utf8>>,
		 swf = 11,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 600,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 50,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 110,
		 extra_att_rate = 1100,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"（近身）对敌人造成105%的伤害，额外附加300点伤害"/utf8>>
}};
get(11,7)->
	{ok,#data_skill{
       id = 11,
       lv = 7,
		 name = <<"十字重斩"/utf8>>,
		 swf = 11,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 700,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 60,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 130,
		 extra_att_rate = 1110,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"（近身）对敌人造成105%的伤害，额外附加350点伤害"/utf8>>
}};
get(11,8)->
	{ok,#data_skill{
       id = 11,
       lv = 8,
		 name = <<"十字重斩"/utf8>>,
		 swf = 11,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 800,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 70,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 150,
		 extra_att_rate = 1120,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"（近身）对敌人造成105%的伤害，额外附加400点伤害"/utf8>>
}};
get(11,9)->
	{ok,#data_skill{
       id = 11,
       lv = 9,
		 name = <<"十字重斩"/utf8>>,
		 swf = 11,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 900,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 80,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 180,
		 extra_att_rate = 1130,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"（近身）对敌人造成105%的伤害，额外附加450点伤害"/utf8>>
}};
get(11,10)->
	{ok,#data_skill{
       id = 11,
       lv = 10,
		 name = <<"十字重斩"/utf8>>,
		 swf = 11,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1000,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 90,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 250,
		 extra_att_rate = 1150,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"（近身）对敌人造成105%的伤害，额外附加500点伤害"/utf8>>
}};
get(12,1)->
	{ok,#data_skill{
       id = 12,
       lv = 1,
		 name = <<"钢铁意志"/utf8>>,
		 swf = 12,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 100,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 10,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 0,
		 attack_range = 3,
		 extra_att = 0,
		 extra_att_rate = 0,
		 buff_ids = [{102,1,1000}],
		 transfer = [12,22,32],
		 explain = <<"临时提升自身防御100点，持续60秒"/utf8>>
}};
get(12,2)->
	{ok,#data_skill{
       id = 12,
       lv = 2,
		 name = <<"钢铁意志"/utf8>>,
		 swf = 12,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 200,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 20,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 0,
		 attack_range = 3,
		 extra_att = 0,
		 extra_att_rate = 0,
		 buff_ids = [{102,2,1000}],
		 transfer = [12,22,32],
		 explain = <<"临时提升自身防御101点，持续60秒"/utf8>>
}};
get(12,3)->
	{ok,#data_skill{
       id = 12,
       lv = 3,
		 name = <<"钢铁意志"/utf8>>,
		 swf = 12,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 300,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 30,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 0,
		 attack_range = 3,
		 extra_att = 0,
		 extra_att_rate = 0,
		 buff_ids = [{102,3,1000}],
		 transfer = [12,22,32],
		 explain = <<"临时提升自身防御102点，持续60秒"/utf8>>
}};
get(12,4)->
	{ok,#data_skill{
       id = 12,
       lv = 4,
		 name = <<"钢铁意志"/utf8>>,
		 swf = 12,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 400,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 40,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 0,
		 attack_range = 3,
		 extra_att = 0,
		 extra_att_rate = 0,
		 buff_ids = [{102,4,1000}],
		 transfer = [12,22,32],
		 explain = <<"临时提升自身防御103点，持续60秒"/utf8>>
}};
get(12,5)->
	{ok,#data_skill{
       id = 12,
       lv = 5,
		 name = <<"钢铁意志"/utf8>>,
		 swf = 12,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 500,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 50,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 0,
		 attack_range = 3,
		 extra_att = 0,
		 extra_att_rate = 0,
		 buff_ids = [{102,5,1000}],
		 transfer = [12,22,32],
		 explain = <<"临时提升自身防御104点，持续60秒"/utf8>>
}};
get(12,6)->
	{ok,#data_skill{
       id = 12,
       lv = 6,
		 name = <<"钢铁意志"/utf8>>,
		 swf = 12,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 600,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 60,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 0,
		 attack_range = 3,
		 extra_att = 0,
		 extra_att_rate = 0,
		 buff_ids = [{102,6,1000}],
		 transfer = [12,22,32],
		 explain = <<"临时提升自身防御105点，持续60秒"/utf8>>
}};
get(12,7)->
	{ok,#data_skill{
       id = 12,
       lv = 7,
		 name = <<"钢铁意志"/utf8>>,
		 swf = 12,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 700,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 70,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 0,
		 attack_range = 3,
		 extra_att = 0,
		 extra_att_rate = 0,
		 buff_ids = [{102,7,1000}],
		 transfer = [12,22,32],
		 explain = <<"临时提升自身防御106点，持续60秒"/utf8>>
}};
get(12,8)->
	{ok,#data_skill{
       id = 12,
       lv = 8,
		 name = <<"钢铁意志"/utf8>>,
		 swf = 12,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 800,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 80,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 0,
		 attack_range = 3,
		 extra_att = 0,
		 extra_att_rate = 0,
		 buff_ids = [{102,8,1000}],
		 transfer = [12,22,32],
		 explain = <<"临时提升自身防御107点，持续60秒"/utf8>>
}};
get(12,9)->
	{ok,#data_skill{
       id = 12,
       lv = 9,
		 name = <<"钢铁意志"/utf8>>,
		 swf = 12,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 900,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 90,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 0,
		 attack_range = 3,
		 extra_att = 0,
		 extra_att_rate = 0,
		 buff_ids = [{102,9,1000}],
		 transfer = [12,22,32],
		 explain = <<"临时提升自身防御108点，持续60秒"/utf8>>
}};
get(12,10)->
	{ok,#data_skill{
       id = 12,
       lv = 10,
		 name = <<"钢铁意志"/utf8>>,
		 swf = 12,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1000,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 100,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 0,
		 attack_range = 3,
		 extra_att = 0,
		 extra_att_rate = 0,
		 buff_ids = [{102,10,1000}],
		 transfer = [12,22,32],
		 explain = <<"临时提升自身防御109点，持续60秒"/utf8>>
}};
get(13,1)->
	{ok,#data_skill{
       id = 13,
       lv = 1,
		 name = <<"幽冥圣手"/utf8>>,
		 swf = 13,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 100,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 15,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 1,
		 attack_range = 5,
		 extra_att = 25,
		 extra_att_rate = 1050,
		 buff_ids = [],
		 transfer = [13,23,33],
		 explain = <<"对目标造成110%伤害，额外附加100点伤害同时将其拖拽至身前（对BOSS无效）"/utf8>>
}};
get(13,2)->
	{ok,#data_skill{
       id = 13,
       lv = 2,
		 name = <<"幽冥圣手"/utf8>>,
		 swf = 13,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 200,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 25,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 1,
		 attack_range = 5,
		 extra_att = 40,
		 extra_att_rate = 1060,
		 buff_ids = [],
		 transfer = [13,23,33],
		 explain = <<"对目标造成110%伤害，额外附加150点伤害同时将其拖拽至身前（对BOSS无效）"/utf8>>
}};
get(13,3)->
	{ok,#data_skill{
       id = 13,
       lv = 3,
		 name = <<"幽冥圣手"/utf8>>,
		 swf = 13,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 300,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 35,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 1,
		 attack_range = 5,
		 extra_att = 55,
		 extra_att_rate = 1070,
		 buff_ids = [],
		 transfer = [13,23,33],
		 explain = <<"对目标造成110%伤害，额外附加200点伤害同时将其拖拽至身前（对BOSS无效）"/utf8>>
}};
get(13,4)->
	{ok,#data_skill{
       id = 13,
       lv = 4,
		 name = <<"幽冥圣手"/utf8>>,
		 swf = 13,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 400,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 45,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 1,
		 attack_range = 5,
		 extra_att = 70,
		 extra_att_rate = 1080,
		 buff_ids = [],
		 transfer = [13,23,33],
		 explain = <<"对目标造成110%伤害，额外附加250点伤害同时将其拖拽至身前（对BOSS无效）"/utf8>>
}};
get(13,5)->
	{ok,#data_skill{
       id = 13,
       lv = 5,
		 name = <<"幽冥圣手"/utf8>>,
		 swf = 13,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 500,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 55,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 1,
		 attack_range = 5,
		 extra_att = 90,
		 extra_att_rate = 1090,
		 buff_ids = [],
		 transfer = [13,23,33],
		 explain = <<"对目标造成110%伤害，额外附加300点伤害同时将其拖拽至身前（对BOSS无效）"/utf8>>
}};
get(13,6)->
	{ok,#data_skill{
       id = 13,
       lv = 6,
		 name = <<"幽冥圣手"/utf8>>,
		 swf = 13,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 600,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 65,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 1,
		 attack_range = 5,
		 extra_att = 110,
		 extra_att_rate = 1100,
		 buff_ids = [],
		 transfer = [13,23,33],
		 explain = <<"对目标造成110%伤害，额外附加350点伤害同时将其拖拽至身前（对BOSS无效）"/utf8>>
}};
get(13,7)->
	{ok,#data_skill{
       id = 13,
       lv = 7,
		 name = <<"幽冥圣手"/utf8>>,
		 swf = 13,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 700,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 75,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 1,
		 attack_range = 5,
		 extra_att = 130,
		 extra_att_rate = 1110,
		 buff_ids = [],
		 transfer = [13,23,33],
		 explain = <<"对目标造成110%伤害，额外附加400点伤害同时将其拖拽至身前（对BOSS无效）"/utf8>>
}};
get(13,8)->
	{ok,#data_skill{
       id = 13,
       lv = 8,
		 name = <<"幽冥圣手"/utf8>>,
		 swf = 13,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 800,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 85,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 1,
		 attack_range = 5,
		 extra_att = 150,
		 extra_att_rate = 1120,
		 buff_ids = [],
		 transfer = [13,23,33],
		 explain = <<"对目标造成110%伤害，额外附加450点伤害同时将其拖拽至身前（对BOSS无效）"/utf8>>
}};
get(13,9)->
	{ok,#data_skill{
       id = 13,
       lv = 9,
		 name = <<"幽冥圣手"/utf8>>,
		 swf = 13,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 900,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 95,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 1,
		 attack_range = 5,
		 extra_att = 180,
		 extra_att_rate = 1130,
		 buff_ids = [],
		 transfer = [13,23,33],
		 explain = <<"对目标造成110%伤害，额外附加500点伤害同时将其拖拽至身前（对BOSS无效）"/utf8>>
}};
get(13,10)->
	{ok,#data_skill{
       id = 13,
       lv = 10,
		 name = <<"幽冥圣手"/utf8>>,
		 swf = 13,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1000,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 100,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 1,
		 attack_range = 5,
		 extra_att = 250,
		 extra_att_rate = 1150,
		 buff_ids = [],
		 transfer = [13,23,33],
		 explain = <<"对目标造成110%伤害，额外附加550点伤害同时将其拖拽至身前（对BOSS无效）"/utf8>>
}};
get(14,1)->
	{ok,#data_skill{
       id = 14,
       lv = 1,
		 name = <<"顺劈斩"/utf8>>,
		 swf = 14,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 100,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 20,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 6000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 50,
		 extra_att_rate = 1200,
		 buff_ids = [],
		 transfer = [14,24,34],
		 explain = <<"（近身）对敌人造成120%的伤害，额外附加100点伤害"/utf8>>
}};
get(14,2)->
	{ok,#data_skill{
       id = 14,
       lv = 2,
		 name = <<"顺劈斩"/utf8>>,
		 swf = 14,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 200,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 30,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 6000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 70,
		 extra_att_rate = 1210,
		 buff_ids = [],
		 transfer = [14,24,34],
		 explain = <<"（近身）对敌人造成120%的伤害，额外附加200点伤害"/utf8>>
}};
get(14,3)->
	{ok,#data_skill{
       id = 14,
       lv = 3,
		 name = <<"顺劈斩"/utf8>>,
		 swf = 14,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 300,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 40,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 6000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 100,
		 extra_att_rate = 1220,
		 buff_ids = [],
		 transfer = [14,24,34],
		 explain = <<"（近身）对敌人造成120%的伤害，额外附加300点伤害"/utf8>>
}};
get(14,4)->
	{ok,#data_skill{
       id = 14,
       lv = 4,
		 name = <<"顺劈斩"/utf8>>,
		 swf = 14,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 400,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 50,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 6000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 150,
		 extra_att_rate = 1230,
		 buff_ids = [],
		 transfer = [14,24,34],
		 explain = <<"（近身）对敌人造成120%的伤害，额外附加400点伤害"/utf8>>
}};
get(14,5)->
	{ok,#data_skill{
       id = 14,
       lv = 5,
		 name = <<"顺劈斩"/utf8>>,
		 swf = 14,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 500,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 60,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 6000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 200,
		 extra_att_rate = 1240,
		 buff_ids = [],
		 transfer = [14,24,34],
		 explain = <<"（近身）对敌人造成120%的伤害，额外附加500点伤害"/utf8>>
}};
get(14,6)->
	{ok,#data_skill{
       id = 14,
       lv = 6,
		 name = <<"顺劈斩"/utf8>>,
		 swf = 14,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 600,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 70,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 6000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 300,
		 extra_att_rate = 1250,
		 buff_ids = [],
		 transfer = [14,24,34],
		 explain = <<"（近身）对敌人造成120%的伤害，额外附加600点伤害"/utf8>>
}};
get(14,7)->
	{ok,#data_skill{
       id = 14,
       lv = 7,
		 name = <<"顺劈斩"/utf8>>,
		 swf = 14,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 700,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 80,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 6000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 400,
		 extra_att_rate = 1260,
		 buff_ids = [],
		 transfer = [14,24,34],
		 explain = <<"（近身）对敌人造成120%的伤害，额外附加700点伤害"/utf8>>
}};
get(14,8)->
	{ok,#data_skill{
       id = 14,
       lv = 8,
		 name = <<"顺劈斩"/utf8>>,
		 swf = 14,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 800,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 90,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 6000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 500,
		 extra_att_rate = 1270,
		 buff_ids = [],
		 transfer = [14,24,34],
		 explain = <<"（近身）对敌人造成120%的伤害，额外附加800点伤害"/utf8>>
}};
get(14,9)->
	{ok,#data_skill{
       id = 14,
       lv = 9,
		 name = <<"顺劈斩"/utf8>>,
		 swf = 14,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 900,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 100,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 6000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 700,
		 extra_att_rate = 1280,
		 buff_ids = [],
		 transfer = [14,24,34],
		 explain = <<"（近身）对敌人造成120%的伤害，额外附加900点伤害"/utf8>>
}};
get(14,10)->
	{ok,#data_skill{
       id = 14,
       lv = 10,
		 name = <<"顺劈斩"/utf8>>,
		 swf = 14,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1000,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 100,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 6000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 1000,
		 extra_att_rate = 1300,
		 buff_ids = [],
		 transfer = [14,24,34],
		 explain = <<"（近身）对敌人造成120%的伤害，额外附加1000点伤害"/utf8>>
}};
get(15,1)->
	{ok,#data_skill{
       id = 15,
       lv = 1,
		 name = <<"剑刃风暴"/utf8>>,
		 swf = 15,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 200,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 25,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 4,
		 attack_range = 4,
		 extra_att = 25,
		 extra_att_rate = 800,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"发动一次近身群攻，范围内4个目标受到伤害"/utf8>>
}};
get(15,2)->
	{ok,#data_skill{
       id = 15,
       lv = 2,
		 name = <<"剑刃风暴"/utf8>>,
		 swf = 15,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 400,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 35,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 4,
		 attack_range = 4,
		 extra_att = 40,
		 extra_att_rate = 820,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"发动一次近身群攻，范围内4个目标受到伤害"/utf8>>
}};
get(15,3)->
	{ok,#data_skill{
       id = 15,
       lv = 3,
		 name = <<"剑刃风暴"/utf8>>,
		 swf = 15,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 600,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 45,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 4,
		 attack_range = 4,
		 extra_att = 55,
		 extra_att_rate = 840,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"发动一次近身群攻，范围内4个目标受到伤害"/utf8>>
}};
get(15,4)->
	{ok,#data_skill{
       id = 15,
       lv = 4,
		 name = <<"剑刃风暴"/utf8>>,
		 swf = 15,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 800,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 55,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 4,
		 attack_range = 4,
		 extra_att = 70,
		 extra_att_rate = 860,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"发动一次近身群攻，范围内4个目标受到伤害"/utf8>>
}};
get(15,5)->
	{ok,#data_skill{
       id = 15,
       lv = 5,
		 name = <<"剑刃风暴"/utf8>>,
		 swf = 15,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1000,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 65,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 4,
		 attack_range = 4,
		 extra_att = 90,
		 extra_att_rate = 880,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"发动一次近身群攻，范围内4个目标受到伤害"/utf8>>
}};
get(15,6)->
	{ok,#data_skill{
       id = 15,
       lv = 6,
		 name = <<"剑刃风暴"/utf8>>,
		 swf = 15,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1200,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 75,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 4,
		 attack_range = 4,
		 extra_att = 110,
		 extra_att_rate = 900,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"发动一次近身群攻，范围内4个目标受到伤害"/utf8>>
}};
get(15,7)->
	{ok,#data_skill{
       id = 15,
       lv = 7,
		 name = <<"剑刃风暴"/utf8>>,
		 swf = 15,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1400,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 85,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 4,
		 attack_range = 4,
		 extra_att = 130,
		 extra_att_rate = 920,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"发动一次近身群攻，范围内4个目标受到伤害"/utf8>>
}};
get(15,8)->
	{ok,#data_skill{
       id = 15,
       lv = 8,
		 name = <<"剑刃风暴"/utf8>>,
		 swf = 15,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1600,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 95,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 4,
		 attack_range = 4,
		 extra_att = 150,
		 extra_att_rate = 940,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"发动一次近身群攻，范围内4个目标受到伤害"/utf8>>
}};
get(15,9)->
	{ok,#data_skill{
       id = 15,
       lv = 9,
		 name = <<"剑刃风暴"/utf8>>,
		 swf = 15,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1800,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 100,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 4,
		 attack_range = 4,
		 extra_att = 180,
		 extra_att_rate = 960,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"发动一次近身群攻，范围内4个目标受到伤害"/utf8>>
}};
get(15,10)->
	{ok,#data_skill{
       id = 15,
       lv = 10,
		 name = <<"剑刃风暴"/utf8>>,
		 swf = 15,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 2000,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 100,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 4,
		 attack_range = 4,
		 extra_att = 250,
		 extra_att_rate = 1000,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"发动一次近身群攻，范围内4个目标受到伤害"/utf8>>
}};
get(21,1)->
	{ok,#data_skill{
       id = 21,
       lv = 1,
		 name = <<"烈风斩"/utf8>>,
		 swf = 21,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 100,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 2,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 25,
		 extra_att_rate = 1050,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"（近身）对敌人造成105%的伤害，额外附加100点伤害"/utf8>>
}};
get(21,2)->
	{ok,#data_skill{
       id = 21,
       lv = 2,
		 name = <<"烈风斩"/utf8>>,
		 swf = 21,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 200,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 10,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 40,
		 extra_att_rate = 1060,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"（近身）对敌人造成105%的伤害，额外附加150点伤害"/utf8>>
}};
get(21,3)->
	{ok,#data_skill{
       id = 21,
       lv = 3,
		 name = <<"烈风斩"/utf8>>,
		 swf = 21,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 300,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 20,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 55,
		 extra_att_rate = 1070,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"（近身）对敌人造成105%的伤害，额外附加200点伤害"/utf8>>
}};
get(21,4)->
	{ok,#data_skill{
       id = 21,
       lv = 4,
		 name = <<"烈风斩"/utf8>>,
		 swf = 21,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 400,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 30,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 70,
		 extra_att_rate = 1080,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"（近身）对敌人造成105%的伤害，额外附加250点伤害"/utf8>>
}};
get(21,5)->
	{ok,#data_skill{
       id = 21,
       lv = 5,
		 name = <<"烈风斩"/utf8>>,
		 swf = 21,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 500,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 40,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 90,
		 extra_att_rate = 1090,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"（近身）对敌人造成105%的伤害，额外附加300点伤害"/utf8>>
}};
get(21,6)->
	{ok,#data_skill{
       id = 21,
       lv = 6,
		 name = <<"烈风斩"/utf8>>,
		 swf = 21,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 600,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 50,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 110,
		 extra_att_rate = 1100,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"（近身）对敌人造成105%的伤害，额外附加350点伤害"/utf8>>
}};
get(21,7)->
	{ok,#data_skill{
       id = 21,
       lv = 7,
		 name = <<"烈风斩"/utf8>>,
		 swf = 21,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 700,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 60,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 130,
		 extra_att_rate = 1110,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"（近身）对敌人造成105%的伤害，额外附加400点伤害"/utf8>>
}};
get(21,8)->
	{ok,#data_skill{
       id = 21,
       lv = 8,
		 name = <<"烈风斩"/utf8>>,
		 swf = 21,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 800,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 70,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 150,
		 extra_att_rate = 1120,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"（近身）对敌人造成105%的伤害，额外附加450点伤害"/utf8>>
}};
get(21,9)->
	{ok,#data_skill{
       id = 21,
       lv = 9,
		 name = <<"烈风斩"/utf8>>,
		 swf = 21,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 900,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 80,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 180,
		 extra_att_rate = 1130,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"（近身）对敌人造成105%的伤害，额外附加500点伤害"/utf8>>
}};
get(21,10)->
	{ok,#data_skill{
       id = 21,
       lv = 10,
		 name = <<"烈风斩"/utf8>>,
		 swf = 21,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1000,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 90,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 250,
		 extra_att_rate = 1150,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"（近身）对敌人造成105%的伤害，额外附加550点伤害"/utf8>>
}};
get(22,1)->
	{ok,#data_skill{
       id = 22,
       lv = 1,
		 name = <<"英灵战锤"/utf8>>,
		 swf = 22,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 100,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 10,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 25,
		 extra_att_rate = 800,
		 buff_ids = [{121,1,1000}],
		 transfer = [12,22,32],
		 explain = <<"（近身）对敌人造成80%的伤害，额外附加50点伤害，同时几率眩晕目标1秒"/utf8>>
}};
get(22,2)->
	{ok,#data_skill{
       id = 22,
       lv = 2,
		 name = <<"英灵战锤"/utf8>>,
		 swf = 22,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 200,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 20,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 40,
		 extra_att_rate = 820,
		 buff_ids = [{121,1,1000}],
		 transfer = [12,22,32],
		 explain = <<"（近身）对敌人造成80%的伤害，额外附加100点伤害，同时几率眩晕目标1秒"/utf8>>
}};
get(22,3)->
	{ok,#data_skill{
       id = 22,
       lv = 3,
		 name = <<"英灵战锤"/utf8>>,
		 swf = 22,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 300,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 30,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 55,
		 extra_att_rate = 840,
		 buff_ids = [{121,1,1000}],
		 transfer = [12,22,32],
		 explain = <<"（近身）对敌人造成80%的伤害，额外附加150点伤害，同时几率眩晕目标1秒"/utf8>>
}};
get(22,4)->
	{ok,#data_skill{
       id = 22,
       lv = 4,
		 name = <<"英灵战锤"/utf8>>,
		 swf = 22,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 400,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 40,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 70,
		 extra_att_rate = 860,
		 buff_ids = [{121,1,1000}],
		 transfer = [12,22,32],
		 explain = <<"（近身）对敌人造成80%的伤害，额外附加200点伤害，同时几率眩晕目标1秒"/utf8>>
}};
get(22,5)->
	{ok,#data_skill{
       id = 22,
       lv = 5,
		 name = <<"英灵战锤"/utf8>>,
		 swf = 22,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 500,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 50,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 90,
		 extra_att_rate = 880,
		 buff_ids = [{121,1,1000}],
		 transfer = [12,22,32],
		 explain = <<"（近身）对敌人造成80%的伤害，额外附加250点伤害，同时几率眩晕目标1秒"/utf8>>
}};
get(22,6)->
	{ok,#data_skill{
       id = 22,
       lv = 6,
		 name = <<"英灵战锤"/utf8>>,
		 swf = 22,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 600,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 60,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 110,
		 extra_att_rate = 900,
		 buff_ids = [{121,1,1000}],
		 transfer = [12,22,32],
		 explain = <<"（近身）对敌人造成80%的伤害，额外附加300点伤害，同时几率眩晕目标1秒"/utf8>>
}};
get(22,7)->
	{ok,#data_skill{
       id = 22,
       lv = 7,
		 name = <<"英灵战锤"/utf8>>,
		 swf = 22,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 700,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 70,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 130,
		 extra_att_rate = 920,
		 buff_ids = [{121,1,1000}],
		 transfer = [12,22,32],
		 explain = <<"（近身）对敌人造成80%的伤害，额外附加350点伤害，同时几率眩晕目标1秒"/utf8>>
}};
get(22,8)->
	{ok,#data_skill{
       id = 22,
       lv = 8,
		 name = <<"英灵战锤"/utf8>>,
		 swf = 22,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 800,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 80,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 150,
		 extra_att_rate = 940,
		 buff_ids = [{121,1,1000}],
		 transfer = [12,22,32],
		 explain = <<"（近身）对敌人造成80%的伤害，额外附加400点伤害，同时几率眩晕目标1秒"/utf8>>
}};
get(22,9)->
	{ok,#data_skill{
       id = 22,
       lv = 9,
		 name = <<"英灵战锤"/utf8>>,
		 swf = 22,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 900,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 90,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 180,
		 extra_att_rate = 960,
		 buff_ids = [{121,1,1000}],
		 transfer = [12,22,32],
		 explain = <<"（近身）对敌人造成80%的伤害，额外附加450点伤害，同时几率眩晕目标1秒"/utf8>>
}};
get(22,10)->
	{ok,#data_skill{
       id = 22,
       lv = 10,
		 name = <<"英灵战锤"/utf8>>,
		 swf = 22,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1000,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 100,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 5000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 250,
		 extra_att_rate = 1000,
		 buff_ids = [{121,1,1000}],
		 transfer = [12,22,32],
		 explain = <<"（近身）对敌人造成80%的伤害，额外附加500点伤害，同时几率眩晕目标1秒"/utf8>>
}};
get(23,1)->
	{ok,#data_skill{
       id = 23,
       lv = 1,
		 name = <<"魅影冲刺"/utf8>>,
		 swf = 23,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 100,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 15,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 15000,
		 attack_target = 2,
		 attack_range = 5,
		 extra_att = 0,
		 extra_att_rate = 0,
		 buff_ids = [],
		 transfer = [13,23,33],
		 explain = <<"向鼠标指向区域冲锋一段距离，升级降低CD"/utf8>>
}};
get(23,2)->
	{ok,#data_skill{
       id = 23,
       lv = 2,
		 name = <<"魅影冲刺"/utf8>>,
		 swf = 23,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 200,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 25,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 14000,
		 attack_target = 2,
		 attack_range = 5,
		 extra_att = 0,
		 extra_att_rate = 0,
		 buff_ids = [],
		 transfer = [13,23,33],
		 explain = <<"向鼠标指向区域冲锋一段距离，升级降低CD"/utf8>>
}};
get(23,3)->
	{ok,#data_skill{
       id = 23,
       lv = 3,
		 name = <<"魅影冲刺"/utf8>>,
		 swf = 23,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 300,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 35,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 13000,
		 attack_target = 2,
		 attack_range = 5,
		 extra_att = 0,
		 extra_att_rate = 0,
		 buff_ids = [],
		 transfer = [13,23,33],
		 explain = <<"向鼠标指向区域冲锋一段距离，升级降低CD"/utf8>>
}};
get(23,4)->
	{ok,#data_skill{
       id = 23,
       lv = 4,
		 name = <<"魅影冲刺"/utf8>>,
		 swf = 23,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 400,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 45,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 12000,
		 attack_target = 2,
		 attack_range = 5,
		 extra_att = 0,
		 extra_att_rate = 0,
		 buff_ids = [],
		 transfer = [13,23,33],
		 explain = <<"向鼠标指向区域冲锋一段距离，升级降低CD"/utf8>>
}};
get(23,5)->
	{ok,#data_skill{
       id = 23,
       lv = 5,
		 name = <<"魅影冲刺"/utf8>>,
		 swf = 23,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 500,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 55,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 11000,
		 attack_target = 2,
		 attack_range = 5,
		 extra_att = 0,
		 extra_att_rate = 0,
		 buff_ids = [],
		 transfer = [13,23,33],
		 explain = <<"向鼠标指向区域冲锋一段距离，升级降低CD"/utf8>>
}};
get(23,6)->
	{ok,#data_skill{
       id = 23,
       lv = 6,
		 name = <<"魅影冲刺"/utf8>>,
		 swf = 23,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 600,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 65,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 2,
		 attack_range = 5,
		 extra_att = 0,
		 extra_att_rate = 0,
		 buff_ids = [],
		 transfer = [13,23,33],
		 explain = <<"向鼠标指向区域冲锋一段距离，升级降低CD"/utf8>>
}};
get(23,7)->
	{ok,#data_skill{
       id = 23,
       lv = 7,
		 name = <<"魅影冲刺"/utf8>>,
		 swf = 23,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 700,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 75,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 9000,
		 attack_target = 2,
		 attack_range = 5,
		 extra_att = 0,
		 extra_att_rate = 0,
		 buff_ids = [],
		 transfer = [13,23,33],
		 explain = <<"向鼠标指向区域冲锋一段距离，升级降低CD"/utf8>>
}};
get(23,8)->
	{ok,#data_skill{
       id = 23,
       lv = 8,
		 name = <<"魅影冲刺"/utf8>>,
		 swf = 23,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 800,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 85,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 8000,
		 attack_target = 2,
		 attack_range = 5,
		 extra_att = 0,
		 extra_att_rate = 0,
		 buff_ids = [],
		 transfer = [13,23,33],
		 explain = <<"向鼠标指向区域冲锋一段距离，升级降低CD"/utf8>>
}};
get(23,9)->
	{ok,#data_skill{
       id = 23,
       lv = 9,
		 name = <<"魅影冲刺"/utf8>>,
		 swf = 23,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 900,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 95,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 7000,
		 attack_target = 2,
		 attack_range = 5,
		 extra_att = 0,
		 extra_att_rate = 0,
		 buff_ids = [],
		 transfer = [13,23,33],
		 explain = <<"向鼠标指向区域冲锋一段距离，升级降低CD"/utf8>>
}};
get(23,10)->
	{ok,#data_skill{
       id = 23,
       lv = 10,
		 name = <<"魅影冲刺"/utf8>>,
		 swf = 23,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1000,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 100,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 6000,
		 attack_target = 2,
		 attack_range = 5,
		 extra_att = 0,
		 extra_att_rate = 0,
		 buff_ids = [],
		 transfer = [13,23,33],
		 explain = <<"向鼠标指向区域冲锋一段距离，升级降低CD"/utf8>>
}};
get(24,1)->
	{ok,#data_skill{
       id = 24,
       lv = 1,
		 name = <<"剧毒打击"/utf8>>,
		 swf = 24,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 100,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 20,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 4000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 25,
		 extra_att_rate = 1000,
		 buff_ids = [{120,1,1000}],
		 transfer = [14,24,34],
		 explain = <<"一次带毒性攻击的近战攻击，使目标持续掉血"/utf8>>
}};
get(24,2)->
	{ok,#data_skill{
       id = 24,
       lv = 2,
		 name = <<"剧毒打击"/utf8>>,
		 swf = 24,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 200,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 30,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 4000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 40,
		 extra_att_rate = 1010,
		 buff_ids = [{120,2,1000}],
		 transfer = [14,24,34],
		 explain = <<"一次带毒性攻击的近战攻击，使目标持续掉血"/utf8>>
}};
get(24,3)->
	{ok,#data_skill{
       id = 24,
       lv = 3,
		 name = <<"剧毒打击"/utf8>>,
		 swf = 24,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 300,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 40,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 4000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 55,
		 extra_att_rate = 1020,
		 buff_ids = [{120,3,1000}],
		 transfer = [14,24,34],
		 explain = <<"一次带毒性攻击的近战攻击，使目标持续掉血"/utf8>>
}};
get(24,4)->
	{ok,#data_skill{
       id = 24,
       lv = 4,
		 name = <<"剧毒打击"/utf8>>,
		 swf = 24,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 400,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 50,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 4000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 70,
		 extra_att_rate = 1030,
		 buff_ids = [{120,4,1000}],
		 transfer = [14,24,34],
		 explain = <<"一次带毒性攻击的近战攻击，使目标持续掉血"/utf8>>
}};
get(24,5)->
	{ok,#data_skill{
       id = 24,
       lv = 5,
		 name = <<"剧毒打击"/utf8>>,
		 swf = 24,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 500,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 60,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 4000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 90,
		 extra_att_rate = 1040,
		 buff_ids = [{120,5,1000}],
		 transfer = [14,24,34],
		 explain = <<"一次带毒性攻击的近战攻击，使目标持续掉血"/utf8>>
}};
get(24,6)->
	{ok,#data_skill{
       id = 24,
       lv = 6,
		 name = <<"剧毒打击"/utf8>>,
		 swf = 24,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 600,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 70,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 4000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 110,
		 extra_att_rate = 1050,
		 buff_ids = [{120,6,1000}],
		 transfer = [14,24,34],
		 explain = <<"一次带毒性攻击的近战攻击，使目标持续掉血"/utf8>>
}};
get(24,7)->
	{ok,#data_skill{
       id = 24,
       lv = 7,
		 name = <<"剧毒打击"/utf8>>,
		 swf = 24,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 700,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 80,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 4000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 130,
		 extra_att_rate = 1060,
		 buff_ids = [{120,7,1000}],
		 transfer = [14,24,34],
		 explain = <<"一次带毒性攻击的近战攻击，使目标持续掉血"/utf8>>
}};
get(24,8)->
	{ok,#data_skill{
       id = 24,
       lv = 8,
		 name = <<"剧毒打击"/utf8>>,
		 swf = 24,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 800,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 90,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 4000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 150,
		 extra_att_rate = 1070,
		 buff_ids = [{120,8,1000}],
		 transfer = [14,24,34],
		 explain = <<"一次带毒性攻击的近战攻击，使目标持续掉血"/utf8>>
}};
get(24,9)->
	{ok,#data_skill{
       id = 24,
       lv = 9,
		 name = <<"剧毒打击"/utf8>>,
		 swf = 24,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 900,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 100,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 4000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 180,
		 extra_att_rate = 1080,
		 buff_ids = [{120,9,1000}],
		 transfer = [14,24,34],
		 explain = <<"一次带毒性攻击的近战攻击，使目标持续掉血"/utf8>>
}};
get(24,10)->
	{ok,#data_skill{
       id = 24,
       lv = 10,
		 name = <<"剧毒打击"/utf8>>,
		 swf = 24,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1000,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 100,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 4000,
		 attack_target = 1,
		 attack_range = 3,
		 extra_att = 250,
		 extra_att_rate = 1100,
		 buff_ids = [{120,10,1000}],
		 transfer = [14,24,34],
		 explain = <<"一次带毒性攻击的近战攻击，使目标持续掉血"/utf8>>
}};
get(25,1)->
	{ok,#data_skill{
       id = 25,
       lv = 1,
		 name = <<"疾风之舞"/utf8>>,
		 swf = 25,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 200,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 25,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 4,
		 attack_range = 4,
		 extra_att = 25,
		 extra_att_rate = 800,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"发动一次近身群攻，范围内4个目标受到伤害"/utf8>>
}};
get(25,2)->
	{ok,#data_skill{
       id = 25,
       lv = 2,
		 name = <<"疾风之舞"/utf8>>,
		 swf = 25,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 400,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 35,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 4,
		 attack_range = 4,
		 extra_att = 40,
		 extra_att_rate = 820,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"发动一次近身群攻，范围内4个目标受到伤害"/utf8>>
}};
get(25,3)->
	{ok,#data_skill{
       id = 25,
       lv = 3,
		 name = <<"疾风之舞"/utf8>>,
		 swf = 25,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 600,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 45,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 4,
		 attack_range = 4,
		 extra_att = 55,
		 extra_att_rate = 840,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"发动一次近身群攻，范围内4个目标受到伤害"/utf8>>
}};
get(25,4)->
	{ok,#data_skill{
       id = 25,
       lv = 4,
		 name = <<"疾风之舞"/utf8>>,
		 swf = 25,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 800,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 55,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 4,
		 attack_range = 4,
		 extra_att = 70,
		 extra_att_rate = 860,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"发动一次近身群攻，范围内4个目标受到伤害"/utf8>>
}};
get(25,5)->
	{ok,#data_skill{
       id = 25,
       lv = 5,
		 name = <<"疾风之舞"/utf8>>,
		 swf = 25,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1000,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 65,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 4,
		 attack_range = 4,
		 extra_att = 90,
		 extra_att_rate = 880,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"发动一次近身群攻，范围内4个目标受到伤害"/utf8>>
}};
get(25,6)->
	{ok,#data_skill{
       id = 25,
       lv = 6,
		 name = <<"疾风之舞"/utf8>>,
		 swf = 25,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1200,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 75,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 4,
		 attack_range = 4,
		 extra_att = 110,
		 extra_att_rate = 900,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"发动一次近身群攻，范围内4个目标受到伤害"/utf8>>
}};
get(25,7)->
	{ok,#data_skill{
       id = 25,
       lv = 7,
		 name = <<"疾风之舞"/utf8>>,
		 swf = 25,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1400,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 85,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 4,
		 attack_range = 4,
		 extra_att = 130,
		 extra_att_rate = 920,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"发动一次近身群攻，范围内4个目标受到伤害"/utf8>>
}};
get(25,8)->
	{ok,#data_skill{
       id = 25,
       lv = 8,
		 name = <<"疾风之舞"/utf8>>,
		 swf = 25,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1600,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 95,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 4,
		 attack_range = 4,
		 extra_att = 150,
		 extra_att_rate = 940,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"发动一次近身群攻，范围内4个目标受到伤害"/utf8>>
}};
get(25,9)->
	{ok,#data_skill{
       id = 25,
       lv = 9,
		 name = <<"疾风之舞"/utf8>>,
		 swf = 25,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1800,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 100,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 4,
		 attack_range = 4,
		 extra_att = 180,
		 extra_att_rate = 960,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"发动一次近身群攻，范围内4个目标受到伤害"/utf8>>
}};
get(25,10)->
	{ok,#data_skill{
       id = 25,
       lv = 10,
		 name = <<"疾风之舞"/utf8>>,
		 swf = 25,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 2000,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 100,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 4,
		 attack_range = 4,
		 extra_att = 250,
		 extra_att_rate = 1000,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"发动一次近身群攻，范围内4个目标受到伤害"/utf8>>
}};
get(31,1)->
	{ok,#data_skill{
       id = 31,
       lv = 1,
		 name = <<"天雷"/utf8>>,
		 swf = 31,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 100,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 2,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 25,
		 extra_att_rate = 1050,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"向目标发射一道雷电，远程12格"/utf8>>
}};
get(31,2)->
	{ok,#data_skill{
       id = 31,
       lv = 2,
		 name = <<"天雷"/utf8>>,
		 swf = 31,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 200,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 10,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 40,
		 extra_att_rate = 1060,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"向目标发射一道雷电，远程12格"/utf8>>
}};
get(31,3)->
	{ok,#data_skill{
       id = 31,
       lv = 3,
		 name = <<"天雷"/utf8>>,
		 swf = 31,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 300,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 20,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 55,
		 extra_att_rate = 1070,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"向目标发射一道雷电，远程12格"/utf8>>
}};
get(31,4)->
	{ok,#data_skill{
       id = 31,
       lv = 4,
		 name = <<"天雷"/utf8>>,
		 swf = 31,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 400,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 30,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 70,
		 extra_att_rate = 1080,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"向目标发射一道雷电，远程12格"/utf8>>
}};
get(31,5)->
	{ok,#data_skill{
       id = 31,
       lv = 5,
		 name = <<"天雷"/utf8>>,
		 swf = 31,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 500,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 40,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 90,
		 extra_att_rate = 1090,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"向目标发射一道雷电，远程12格"/utf8>>
}};
get(31,6)->
	{ok,#data_skill{
       id = 31,
       lv = 6,
		 name = <<"天雷"/utf8>>,
		 swf = 31,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 600,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 50,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 110,
		 extra_att_rate = 1100,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"向目标发射一道雷电，远程12格"/utf8>>
}};
get(31,7)->
	{ok,#data_skill{
       id = 31,
       lv = 7,
		 name = <<"天雷"/utf8>>,
		 swf = 31,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 700,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 60,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 130,
		 extra_att_rate = 1110,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"向目标发射一道雷电，远程12格"/utf8>>
}};
get(31,8)->
	{ok,#data_skill{
       id = 31,
       lv = 8,
		 name = <<"天雷"/utf8>>,
		 swf = 31,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 800,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 70,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 150,
		 extra_att_rate = 1120,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"向目标发射一道雷电，远程12格"/utf8>>
}};
get(31,9)->
	{ok,#data_skill{
       id = 31,
       lv = 9,
		 name = <<"天雷"/utf8>>,
		 swf = 31,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 900,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 80,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 180,
		 extra_att_rate = 1130,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"向目标发射一道雷电，远程12格"/utf8>>
}};
get(31,10)->
	{ok,#data_skill{
       id = 31,
       lv = 10,
		 name = <<"天雷"/utf8>>,
		 swf = 31,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1000,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 90,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 1000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 250,
		 extra_att_rate = 1150,
		 buff_ids = [],
		 transfer = [11,21,31],
		 explain = <<"向目标发射一道雷电，远程12格"/utf8>>
}};
get(32,1)->
	{ok,#data_skill{
       id = 32,
       lv = 1,
		 name = <<"克敌先机"/utf8>>,
		 swf = 32,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 100,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 10,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 4000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 25,
		 extra_att_rate = 1050,
		 buff_ids = [{113,1,1000}],
		 transfer = [12,22,32],
		 explain = <<"降低目标闪避"/utf8>>
}};
get(32,2)->
	{ok,#data_skill{
       id = 32,
       lv = 2,
		 name = <<"克敌先机"/utf8>>,
		 swf = 32,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 200,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 20,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 4000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 40,
		 extra_att_rate = 1060,
		 buff_ids = [{113,2,1000}],
		 transfer = [12,22,32],
		 explain = <<"降低目标闪避"/utf8>>
}};
get(32,3)->
	{ok,#data_skill{
       id = 32,
       lv = 3,
		 name = <<"克敌先机"/utf8>>,
		 swf = 32,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 300,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 30,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 4000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 55,
		 extra_att_rate = 1070,
		 buff_ids = [{113,3,1000}],
		 transfer = [12,22,32],
		 explain = <<"降低目标闪避"/utf8>>
}};
get(32,4)->
	{ok,#data_skill{
       id = 32,
       lv = 4,
		 name = <<"克敌先机"/utf8>>,
		 swf = 32,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 400,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 40,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 4000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 70,
		 extra_att_rate = 1080,
		 buff_ids = [{113,4,1000}],
		 transfer = [12,22,32],
		 explain = <<"降低目标闪避"/utf8>>
}};
get(32,5)->
	{ok,#data_skill{
       id = 32,
       lv = 5,
		 name = <<"克敌先机"/utf8>>,
		 swf = 32,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 500,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 50,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 4000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 90,
		 extra_att_rate = 1090,
		 buff_ids = [{113,5,1000}],
		 transfer = [12,22,32],
		 explain = <<"降低目标闪避"/utf8>>
}};
get(32,6)->
	{ok,#data_skill{
       id = 32,
       lv = 6,
		 name = <<"克敌先机"/utf8>>,
		 swf = 32,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 600,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 60,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 4000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 110,
		 extra_att_rate = 1100,
		 buff_ids = [{113,6,1000}],
		 transfer = [12,22,32],
		 explain = <<"降低目标闪避"/utf8>>
}};
get(32,7)->
	{ok,#data_skill{
       id = 32,
       lv = 7,
		 name = <<"克敌先机"/utf8>>,
		 swf = 32,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 700,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 70,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 4000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 130,
		 extra_att_rate = 1110,
		 buff_ids = [{113,7,1000}],
		 transfer = [12,22,32],
		 explain = <<"降低目标闪避"/utf8>>
}};
get(32,8)->
	{ok,#data_skill{
       id = 32,
       lv = 8,
		 name = <<"克敌先机"/utf8>>,
		 swf = 32,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 800,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 80,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 4000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 150,
		 extra_att_rate = 1120,
		 buff_ids = [{113,8,1000}],
		 transfer = [12,22,32],
		 explain = <<"降低目标闪避"/utf8>>
}};
get(32,9)->
	{ok,#data_skill{
       id = 32,
       lv = 9,
		 name = <<"克敌先机"/utf8>>,
		 swf = 32,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 900,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 90,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 4000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 180,
		 extra_att_rate = 1130,
		 buff_ids = [{113,9,1000}],
		 transfer = [12,22,32],
		 explain = <<"降低目标闪避"/utf8>>
}};
get(32,10)->
	{ok,#data_skill{
       id = 32,
       lv = 10,
		 name = <<"克敌先机"/utf8>>,
		 swf = 32,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1000,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 100,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 4000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 250,
		 extra_att_rate = 1150,
		 buff_ids = [{113,10,1000}],
		 transfer = [12,22,32],
		 explain = <<"降低目标闪避"/utf8>>
}};
get(33,1)->
	{ok,#data_skill{
       id = 33,
       lv = 1,
		 name = <<"伤害加深"/utf8>>,
		 swf = 33,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 100,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 15,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 6000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 25,
		 extra_att_rate = 1050,
		 buff_ids = [{111,1,1000}],
		 transfer = [13,23,33],
		 explain = <<"降低目标防御力"/utf8>>
}};
get(33,2)->
	{ok,#data_skill{
       id = 33,
       lv = 2,
		 name = <<"伤害加深"/utf8>>,
		 swf = 33,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 200,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 25,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 6000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 40,
		 extra_att_rate = 1060,
		 buff_ids = [{111,2,1000}],
		 transfer = [13,23,33],
		 explain = <<"降低目标防御力"/utf8>>
}};
get(33,3)->
	{ok,#data_skill{
       id = 33,
       lv = 3,
		 name = <<"伤害加深"/utf8>>,
		 swf = 33,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 300,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 35,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 6000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 55,
		 extra_att_rate = 1070,
		 buff_ids = [{111,3,1000}],
		 transfer = [13,23,33],
		 explain = <<"降低目标防御力"/utf8>>
}};
get(33,4)->
	{ok,#data_skill{
       id = 33,
       lv = 4,
		 name = <<"伤害加深"/utf8>>,
		 swf = 33,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 400,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 45,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 6000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 70,
		 extra_att_rate = 1080,
		 buff_ids = [{111,4,1000}],
		 transfer = [13,23,33],
		 explain = <<"降低目标防御力"/utf8>>
}};
get(33,5)->
	{ok,#data_skill{
       id = 33,
       lv = 5,
		 name = <<"伤害加深"/utf8>>,
		 swf = 33,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 500,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 55,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 6000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 90,
		 extra_att_rate = 1090,
		 buff_ids = [{111,5,1000}],
		 transfer = [13,23,33],
		 explain = <<"降低目标防御力"/utf8>>
}};
get(33,6)->
	{ok,#data_skill{
       id = 33,
       lv = 6,
		 name = <<"伤害加深"/utf8>>,
		 swf = 33,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 600,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 65,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 6000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 110,
		 extra_att_rate = 1100,
		 buff_ids = [{111,6,1000}],
		 transfer = [13,23,33],
		 explain = <<"降低目标防御力"/utf8>>
}};
get(33,7)->
	{ok,#data_skill{
       id = 33,
       lv = 7,
		 name = <<"伤害加深"/utf8>>,
		 swf = 33,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 700,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 75,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 6000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 130,
		 extra_att_rate = 1110,
		 buff_ids = [{111,7,1000}],
		 transfer = [13,23,33],
		 explain = <<"降低目标防御力"/utf8>>
}};
get(33,8)->
	{ok,#data_skill{
       id = 33,
       lv = 8,
		 name = <<"伤害加深"/utf8>>,
		 swf = 33,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 800,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 85,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 6000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 150,
		 extra_att_rate = 1120,
		 buff_ids = [{111,8,1000}],
		 transfer = [13,23,33],
		 explain = <<"降低目标防御力"/utf8>>
}};
get(33,9)->
	{ok,#data_skill{
       id = 33,
       lv = 9,
		 name = <<"伤害加深"/utf8>>,
		 swf = 33,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 900,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 95,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 6000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 180,
		 extra_att_rate = 1130,
		 buff_ids = [{111,9,1000}],
		 transfer = [13,23,33],
		 explain = <<"降低目标防御力"/utf8>>
}};
get(33,10)->
	{ok,#data_skill{
       id = 33,
       lv = 10,
		 name = <<"伤害加深"/utf8>>,
		 swf = 33,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1000,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 100,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 6000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 250,
		 extra_att_rate = 1150,
		 buff_ids = [{111,10,1000}],
		 transfer = [13,23,33],
		 explain = <<"降低目标防御力"/utf8>>
}};
get(34,1)->
	{ok,#data_skill{
       id = 34,
       lv = 1,
		 name = <<"爆裂"/utf8>>,
		 swf = 34,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 100,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 20,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 12000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 150,
		 extra_att_rate = 1150,
		 buff_ids = [],
		 transfer = [14,24,34],
		 explain = <<"强力远程攻击，12格"/utf8>>
}};
get(34,2)->
	{ok,#data_skill{
       id = 34,
       lv = 2,
		 name = <<"爆裂"/utf8>>,
		 swf = 34,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 200,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 30,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 12000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 300,
		 extra_att_rate = 1200,
		 buff_ids = [],
		 transfer = [14,24,34],
		 explain = <<"强力远程攻击，12格"/utf8>>
}};
get(34,3)->
	{ok,#data_skill{
       id = 34,
       lv = 3,
		 name = <<"爆裂"/utf8>>,
		 swf = 34,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 300,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 40,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 12000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 450,
		 extra_att_rate = 1210,
		 buff_ids = [],
		 transfer = [14,24,34],
		 explain = <<"强力远程攻击，12格"/utf8>>
}};
get(34,4)->
	{ok,#data_skill{
       id = 34,
       lv = 4,
		 name = <<"爆裂"/utf8>>,
		 swf = 34,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 400,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 50,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 12000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 600,
		 extra_att_rate = 1220,
		 buff_ids = [],
		 transfer = [14,24,34],
		 explain = <<"强力远程攻击，12格"/utf8>>
}};
get(34,5)->
	{ok,#data_skill{
       id = 34,
       lv = 5,
		 name = <<"爆裂"/utf8>>,
		 swf = 34,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 500,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 60,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 12000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 750,
		 extra_att_rate = 1230,
		 buff_ids = [],
		 transfer = [14,24,34],
		 explain = <<"强力远程攻击，12格"/utf8>>
}};
get(34,6)->
	{ok,#data_skill{
       id = 34,
       lv = 6,
		 name = <<"爆裂"/utf8>>,
		 swf = 34,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 600,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 70,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 12000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 900,
		 extra_att_rate = 1240,
		 buff_ids = [],
		 transfer = [14,24,34],
		 explain = <<"强力远程攻击，12格"/utf8>>
}};
get(34,7)->
	{ok,#data_skill{
       id = 34,
       lv = 7,
		 name = <<"爆裂"/utf8>>,
		 swf = 34,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 700,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 80,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 12000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 1050,
		 extra_att_rate = 1250,
		 buff_ids = [],
		 transfer = [14,24,34],
		 explain = <<"强力远程攻击，12格"/utf8>>
}};
get(34,8)->
	{ok,#data_skill{
       id = 34,
       lv = 8,
		 name = <<"爆裂"/utf8>>,
		 swf = 34,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 800,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 90,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 12000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 1200,
		 extra_att_rate = 1260,
		 buff_ids = [],
		 transfer = [14,24,34],
		 explain = <<"强力远程攻击，12格"/utf8>>
}};
get(34,9)->
	{ok,#data_skill{
       id = 34,
       lv = 9,
		 name = <<"爆裂"/utf8>>,
		 swf = 34,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 900,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 100,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 12000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 1350,
		 extra_att_rate = 1270,
		 buff_ids = [],
		 transfer = [14,24,34],
		 explain = <<"强力远程攻击，12格"/utf8>>
}};
get(34,10)->
	{ok,#data_skill{
       id = 34,
       lv = 10,
		 name = <<"爆裂"/utf8>>,
		 swf = 34,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1000,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 100,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 12000,
		 attack_target = 1,
		 attack_range = 12,
		 extra_att = 1500,
		 extra_att_rate = 1280,
		 buff_ids = [],
		 transfer = [14,24,34],
		 explain = <<"强力远程攻击，12格"/utf8>>
}};
get(35,1)->
	{ok,#data_skill{
       id = 35,
       lv = 1,
		 name = <<"闪电风暴"/utf8>>,
		 swf = 35,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 200,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 25,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 6,
		 attack_range = 5,
		 extra_att = 25,
		 extra_att_rate = 800,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"群体攻击，5格范围内6个单位受到伤害"/utf8>>
}};
get(35,2)->
	{ok,#data_skill{
       id = 35,
       lv = 2,
		 name = <<"闪电风暴"/utf8>>,
		 swf = 35,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 400,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 35,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 6,
		 attack_range = 5,
		 extra_att = 40,
		 extra_att_rate = 820,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"群体攻击，5格范围内6个单位受到伤害"/utf8>>
}};
get(35,3)->
	{ok,#data_skill{
       id = 35,
       lv = 3,
		 name = <<"闪电风暴"/utf8>>,
		 swf = 35,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 600,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 45,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 6,
		 attack_range = 5,
		 extra_att = 55,
		 extra_att_rate = 840,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"群体攻击，5格范围内6个单位受到伤害"/utf8>>
}};
get(35,4)->
	{ok,#data_skill{
       id = 35,
       lv = 4,
		 name = <<"闪电风暴"/utf8>>,
		 swf = 35,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 800,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 55,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 6,
		 attack_range = 5,
		 extra_att = 70,
		 extra_att_rate = 860,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"群体攻击，5格范围内6个单位受到伤害"/utf8>>
}};
get(35,5)->
	{ok,#data_skill{
       id = 35,
       lv = 5,
		 name = <<"闪电风暴"/utf8>>,
		 swf = 35,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1000,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 65,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 6,
		 attack_range = 5,
		 extra_att = 90,
		 extra_att_rate = 880,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"群体攻击，5格范围内6个单位受到伤害"/utf8>>
}};
get(35,6)->
	{ok,#data_skill{
       id = 35,
       lv = 6,
		 name = <<"闪电风暴"/utf8>>,
		 swf = 35,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1200,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 75,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 6,
		 attack_range = 5,
		 extra_att = 110,
		 extra_att_rate = 900,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"群体攻击，5格范围内6个单位受到伤害"/utf8>>
}};
get(35,7)->
	{ok,#data_skill{
       id = 35,
       lv = 7,
		 name = <<"闪电风暴"/utf8>>,
		 swf = 35,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1400,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 85,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 6,
		 attack_range = 5,
		 extra_att = 130,
		 extra_att_rate = 920,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"群体攻击，5格范围内6个单位受到伤害"/utf8>>
}};
get(35,8)->
	{ok,#data_skill{
       id = 35,
       lv = 8,
		 name = <<"闪电风暴"/utf8>>,
		 swf = 35,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1600,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 95,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 6,
		 attack_range = 5,
		 extra_att = 150,
		 extra_att_rate = 940,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"群体攻击，5格范围内6个单位受到伤害"/utf8>>
}};
get(35,9)->
	{ok,#data_skill{
       id = 35,
       lv = 9,
		 name = <<"闪电风暴"/utf8>>,
		 swf = 35,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 1800,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 100,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 6,
		 attack_range = 5,
		 extra_att = 180,
		 extra_att_rate = 960,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"群体攻击，5格范围内6个单位受到伤害"/utf8>>
}};
get(35,10)->
	{ok,#data_skill{
       id = 35,
       lv = 10,
		 name = <<"闪电风暴"/utf8>>,
		 swf = 35,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 2000,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 100,
		 need_mp = 20,
		 need_cast_time = 0,
		 cd = 10000,
		 attack_target = 6,
		 attack_range = 5,
		 extra_att = 250,
		 extra_att_rate = 1000,
		 buff_ids = [],
		 transfer = [15,25,35],
		 explain = <<"群体攻击，5格范围内6个单位受到伤害"/utf8>>
}};
get(_Id,_Lv)->
	{error,no_match}.
