-module(data_skill_ed).
-include("skill.hrl").
-export([ids/0,get/2]).

ids()->
	[103,201,202,203,301,302,303,1101,1102].

get(103,1)->
	{ok,#data_skill_ed{
       id = 103,
		 lv = 1,
		 name = <<"防御"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 5,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 100,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"防御"/utf8>>
	}};
get(103,2)->
	{ok,#data_skill_ed{
       id = 103,
		 lv = 2,
		 name = <<"防御"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 10,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 200,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"防御"/utf8>>
	}};
get(103,3)->
	{ok,#data_skill_ed{
       id = 103,
		 lv = 3,
		 name = <<"防御"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 15,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 300,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"防御"/utf8>>
	}};
get(103,4)->
	{ok,#data_skill_ed{
       id = 103,
		 lv = 4,
		 name = <<"防御"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 20,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 400,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"防御"/utf8>>
	}};
get(103,5)->
	{ok,#data_skill_ed{
       id = 103,
		 lv = 5,
		 name = <<"防御"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 25,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 500,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"防御"/utf8>>
	}};
get(103,6)->
	{ok,#data_skill_ed{
       id = 103,
		 lv = 6,
		 name = <<"防御"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 30,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 600,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"防御"/utf8>>
	}};
get(103,7)->
	{ok,#data_skill_ed{
       id = 103,
		 lv = 7,
		 name = <<"防御"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 35,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 700,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"防御"/utf8>>
	}};
get(103,8)->
	{ok,#data_skill_ed{
       id = 103,
		 lv = 8,
		 name = <<"防御"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 40,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 800,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"防御"/utf8>>
	}};
get(103,9)->
	{ok,#data_skill_ed{
       id = 103,
		 lv = 9,
		 name = <<"防御"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 45,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 900,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"防御"/utf8>>
	}};
get(103,10)->
	{ok,#data_skill_ed{
       id = 103,
		 lv = 10,
		 name = <<"防御"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 50,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 1000,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"防御"/utf8>>
	}};
get(201,1)->
	{ok,#data_skill_ed{
       id = 201,
		 lv = 1,
		 name = <<"命中"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 5,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 100,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"命中"/utf8>>
	}};
get(201,2)->
	{ok,#data_skill_ed{
       id = 201,
		 lv = 2,
		 name = <<"命中"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 10,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 200,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"命中"/utf8>>
	}};
get(201,3)->
	{ok,#data_skill_ed{
       id = 201,
		 lv = 3,
		 name = <<"命中"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 15,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 300,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"命中"/utf8>>
	}};
get(201,4)->
	{ok,#data_skill_ed{
       id = 201,
		 lv = 4,
		 name = <<"命中"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 20,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 400,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"命中"/utf8>>
	}};
get(201,5)->
	{ok,#data_skill_ed{
       id = 201,
		 lv = 5,
		 name = <<"命中"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 25,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 500,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"命中"/utf8>>
	}};
get(201,6)->
	{ok,#data_skill_ed{
       id = 201,
		 lv = 6,
		 name = <<"命中"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 30,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 600,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"命中"/utf8>>
	}};
get(201,7)->
	{ok,#data_skill_ed{
       id = 201,
		 lv = 7,
		 name = <<"命中"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 35,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 700,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"命中"/utf8>>
	}};
get(201,8)->
	{ok,#data_skill_ed{
       id = 201,
		 lv = 8,
		 name = <<"命中"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 40,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 800,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"命中"/utf8>>
	}};
get(201,9)->
	{ok,#data_skill_ed{
       id = 201,
		 lv = 9,
		 name = <<"命中"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 45,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 900,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"命中"/utf8>>
	}};
get(201,10)->
	{ok,#data_skill_ed{
       id = 201,
		 lv = 10,
		 name = <<"命中"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 50,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 1000,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"命中"/utf8>>
	}};
get(202,1)->
	{ok,#data_skill_ed{
       id = 202,
		 lv = 1,
		 name = <<"闪避"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 5,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 10,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"闪避"/utf8>>
	}};
get(202,2)->
	{ok,#data_skill_ed{
       id = 202,
		 lv = 2,
		 name = <<"闪避"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 10,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 20,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"闪避"/utf8>>
	}};
get(202,3)->
	{ok,#data_skill_ed{
       id = 202,
		 lv = 3,
		 name = <<"闪避"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 15,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 30,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"闪避"/utf8>>
	}};
get(202,4)->
	{ok,#data_skill_ed{
       id = 202,
		 lv = 4,
		 name = <<"闪避"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 20,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 40,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"闪避"/utf8>>
	}};
get(202,5)->
	{ok,#data_skill_ed{
       id = 202,
		 lv = 5,
		 name = <<"闪避"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 25,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 50,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"闪避"/utf8>>
	}};
get(202,6)->
	{ok,#data_skill_ed{
       id = 202,
		 lv = 6,
		 name = <<"闪避"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 30,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 60,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"闪避"/utf8>>
	}};
get(202,7)->
	{ok,#data_skill_ed{
       id = 202,
		 lv = 7,
		 name = <<"闪避"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 35,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 70,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"闪避"/utf8>>
	}};
get(202,8)->
	{ok,#data_skill_ed{
       id = 202,
		 lv = 8,
		 name = <<"闪避"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 40,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 80,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"闪避"/utf8>>
	}};
get(202,9)->
	{ok,#data_skill_ed{
       id = 202,
		 lv = 9,
		 name = <<"闪避"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 45,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 90,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"闪避"/utf8>>
	}};
get(202,10)->
	{ok,#data_skill_ed{
       id = 202,
		 lv = 10,
		 name = <<"闪避"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 50,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 100,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"闪避"/utf8>>
	}};
get(203,1)->
	{ok,#data_skill_ed{
       id = 203,
		 lv = 1,
		 name = <<"暴击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 5,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 100,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"暴击"/utf8>>
	}};
get(203,2)->
	{ok,#data_skill_ed{
       id = 203,
		 lv = 2,
		 name = <<"暴击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 10,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 200,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"暴击"/utf8>>
	}};
get(203,3)->
	{ok,#data_skill_ed{
       id = 203,
		 lv = 3,
		 name = <<"暴击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 15,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 300,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"暴击"/utf8>>
	}};
get(203,4)->
	{ok,#data_skill_ed{
       id = 203,
		 lv = 4,
		 name = <<"暴击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 20,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 400,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"暴击"/utf8>>
	}};
get(203,5)->
	{ok,#data_skill_ed{
       id = 203,
		 lv = 5,
		 name = <<"暴击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 25,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 500,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"暴击"/utf8>>
	}};
get(203,6)->
	{ok,#data_skill_ed{
       id = 203,
		 lv = 6,
		 name = <<"暴击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 30,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 600,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"暴击"/utf8>>
	}};
get(203,7)->
	{ok,#data_skill_ed{
       id = 203,
		 lv = 7,
		 name = <<"暴击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 35,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 700,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"暴击"/utf8>>
	}};
get(203,8)->
	{ok,#data_skill_ed{
       id = 203,
		 lv = 8,
		 name = <<"暴击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 40,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 800,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"暴击"/utf8>>
	}};
get(203,9)->
	{ok,#data_skill_ed{
       id = 203,
		 lv = 9,
		 name = <<"暴击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 45,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 900,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"暴击"/utf8>>
	}};
get(203,10)->
	{ok,#data_skill_ed{
       id = 203,
		 lv = 10,
		 name = <<"暴击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 2,
		 need_lv = 50,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 1000,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"暴击"/utf8>>
	}};
get(301,1)->
	{ok,#data_skill_ed{
       id = 301,
		 lv = 1,
		 name = <<"攻击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 5,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 100,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"攻击"/utf8>>
	}};
get(301,2)->
	{ok,#data_skill_ed{
       id = 301,
		 lv = 2,
		 name = <<"攻击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 10,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 200,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"攻击"/utf8>>
	}};
get(301,3)->
	{ok,#data_skill_ed{
       id = 301,
		 lv = 3,
		 name = <<"攻击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 15,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 300,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"攻击"/utf8>>
	}};
get(301,4)->
	{ok,#data_skill_ed{
       id = 301,
		 lv = 4,
		 name = <<"攻击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 20,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 400,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"攻击"/utf8>>
	}};
get(301,5)->
	{ok,#data_skill_ed{
       id = 301,
		 lv = 5,
		 name = <<"攻击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 25,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 500,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"攻击"/utf8>>
	}};
get(301,6)->
	{ok,#data_skill_ed{
       id = 301,
		 lv = 6,
		 name = <<"攻击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 30,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 600,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"攻击"/utf8>>
	}};
get(301,7)->
	{ok,#data_skill_ed{
       id = 301,
		 lv = 7,
		 name = <<"攻击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 35,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 700,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"攻击"/utf8>>
	}};
get(301,8)->
	{ok,#data_skill_ed{
       id = 301,
		 lv = 8,
		 name = <<"攻击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 40,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 800,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"攻击"/utf8>>
	}};
get(301,9)->
	{ok,#data_skill_ed{
       id = 301,
		 lv = 9,
		 name = <<"攻击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 45,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 900,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"攻击"/utf8>>
	}};
get(301,10)->
	{ok,#data_skill_ed{
       id = 301,
		 lv = 10,
		 name = <<"攻击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 50,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 1000,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"攻击"/utf8>>
	}};
get(302,1)->
	{ok,#data_skill_ed{
       id = 302,
		 lv = 1,
		 name = <<"魔法"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 5,
		cd = 0,
		hp = 0,
		mp = 100,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"魔法"/utf8>>
	}};
get(302,2)->
	{ok,#data_skill_ed{
       id = 302,
		 lv = 2,
		 name = <<"魔法"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 10,
		cd = 0,
		hp = 0,
		mp = 200,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"魔法"/utf8>>
	}};
get(302,3)->
	{ok,#data_skill_ed{
       id = 302,
		 lv = 3,
		 name = <<"魔法"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 15,
		cd = 0,
		hp = 0,
		mp = 300,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"魔法"/utf8>>
	}};
get(302,4)->
	{ok,#data_skill_ed{
       id = 302,
		 lv = 4,
		 name = <<"魔法"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 20,
		cd = 0,
		hp = 0,
		mp = 400,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"魔法"/utf8>>
	}};
get(302,5)->
	{ok,#data_skill_ed{
       id = 302,
		 lv = 5,
		 name = <<"魔法"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 25,
		cd = 0,
		hp = 0,
		mp = 500,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"魔法"/utf8>>
	}};
get(302,6)->
	{ok,#data_skill_ed{
       id = 302,
		 lv = 6,
		 name = <<"魔法"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 30,
		cd = 0,
		hp = 0,
		mp = 600,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"魔法"/utf8>>
	}};
get(302,7)->
	{ok,#data_skill_ed{
       id = 302,
		 lv = 7,
		 name = <<"魔法"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 35,
		cd = 0,
		hp = 0,
		mp = 700,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"魔法"/utf8>>
	}};
get(302,8)->
	{ok,#data_skill_ed{
       id = 302,
		 lv = 8,
		 name = <<"魔法"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 40,
		cd = 0,
		hp = 0,
		mp = 800,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"魔法"/utf8>>
	}};
get(302,9)->
	{ok,#data_skill_ed{
       id = 302,
		 lv = 9,
		 name = <<"魔法"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 45,
		cd = 0,
		hp = 0,
		mp = 900,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"魔法"/utf8>>
	}};
get(302,10)->
	{ok,#data_skill_ed{
       id = 302,
		 lv = 10,
		 name = <<"魔法"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 50,
		cd = 0,
		hp = 0,
		mp = 1000,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"魔法"/utf8>>
	}};
get(303,1)->
	{ok,#data_skill_ed{
       id = 303,
		 lv = 1,
		 name = <<"闪避"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 5,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 100,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"闪避"/utf8>>
	}};
get(303,2)->
	{ok,#data_skill_ed{
       id = 303,
		 lv = 2,
		 name = <<"闪避"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 10,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 200,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"闪避"/utf8>>
	}};
get(303,3)->
	{ok,#data_skill_ed{
       id = 303,
		 lv = 3,
		 name = <<"闪避"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 15,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 300,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"闪避"/utf8>>
	}};
get(303,4)->
	{ok,#data_skill_ed{
       id = 303,
		 lv = 4,
		 name = <<"闪避"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 20,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 400,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"闪避"/utf8>>
	}};
get(303,5)->
	{ok,#data_skill_ed{
       id = 303,
		 lv = 5,
		 name = <<"闪避"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 25,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 500,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"闪避"/utf8>>
	}};
get(303,6)->
	{ok,#data_skill_ed{
       id = 303,
		 lv = 6,
		 name = <<"闪避"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 30,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 600,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"闪避"/utf8>>
	}};
get(303,7)->
	{ok,#data_skill_ed{
       id = 303,
		 lv = 7,
		 name = <<"闪避"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 35,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 700,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"闪避"/utf8>>
	}};
get(303,8)->
	{ok,#data_skill_ed{
       id = 303,
		 lv = 8,
		 name = <<"闪避"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 40,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 800,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"闪避"/utf8>>
	}};
get(303,9)->
	{ok,#data_skill_ed{
       id = 303,
		 lv = 9,
		 name = <<"闪避"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 45,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 900,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"闪避"/utf8>>
	}};
get(303,10)->
	{ok,#data_skill_ed{
       id = 303,
		 lv = 10,
		 name = <<"闪避"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 3,
		 need_lv = 50,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 1000,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [103,203,303],
		 explain = <<"闪避"/utf8>>
	}};
get(1101,1)->
	{ok,#data_skill_ed{
       id = 1101,
		 lv = 1,
		 name = <<"强壮"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 5,
		cd = 0,
		hp = 100,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"强壮"/utf8>>
	}};
get(1101,2)->
	{ok,#data_skill_ed{
       id = 1101,
		 lv = 2,
		 name = <<"强壮"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 10,
		cd = 0,
		hp = 200,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"强壮"/utf8>>
	}};
get(1101,3)->
	{ok,#data_skill_ed{
       id = 1101,
		 lv = 3,
		 name = <<"强壮"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 15,
		cd = 0,
		hp = 300,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"强壮"/utf8>>
	}};
get(1101,4)->
	{ok,#data_skill_ed{
       id = 1101,
		 lv = 4,
		 name = <<"强壮"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 20,
		cd = 0,
		hp = 400,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"强壮"/utf8>>
	}};
get(1101,5)->
	{ok,#data_skill_ed{
       id = 1101,
		 lv = 5,
		 name = <<"强壮"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 25,
		cd = 0,
		hp = 500,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"强壮"/utf8>>
	}};
get(1101,6)->
	{ok,#data_skill_ed{
       id = 1101,
		 lv = 6,
		 name = <<"强壮"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 30,
		cd = 0,
		hp = 600,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"强壮"/utf8>>
	}};
get(1101,7)->
	{ok,#data_skill_ed{
       id = 1101,
		 lv = 7,
		 name = <<"强壮"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 35,
		cd = 0,
		hp = 700,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"强壮"/utf8>>
	}};
get(1101,8)->
	{ok,#data_skill_ed{
       id = 1101,
		 lv = 8,
		 name = <<"强壮"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 40,
		cd = 0,
		hp = 800,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"强壮"/utf8>>
	}};
get(1101,9)->
	{ok,#data_skill_ed{
       id = 1101,
		 lv = 9,
		 name = <<"强壮"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 45,
		cd = 0,
		hp = 900,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"强壮"/utf8>>
	}};
get(1101,10)->
	{ok,#data_skill_ed{
       id = 1101,
		 lv = 10,
		 name = <<"强壮"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 50,
		cd = 0,
		hp = 1000,
		mp = 0,
		att = 0,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [101,201,301],
		 explain = <<"强壮"/utf8>>
	}};
get(1102,1)->
	{ok,#data_skill_ed{
       id = 1102,
		 lv = 1,
		 name = <<"攻击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 5,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 100,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"攻击"/utf8>>
	}};
get(1102,2)->
	{ok,#data_skill_ed{
       id = 1102,
		 lv = 2,
		 name = <<"攻击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 10,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 200,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"攻击"/utf8>>
	}};
get(1102,3)->
	{ok,#data_skill_ed{
       id = 1102,
		 lv = 3,
		 name = <<"攻击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 15,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 300,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"攻击"/utf8>>
	}};
get(1102,4)->
	{ok,#data_skill_ed{
       id = 1102,
		 lv = 4,
		 name = <<"攻击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 20,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 400,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"攻击"/utf8>>
	}};
get(1102,5)->
	{ok,#data_skill_ed{
       id = 1102,
		 lv = 5,
		 name = <<"攻击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 25,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 500,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"攻击"/utf8>>
	}};
get(1102,6)->
	{ok,#data_skill_ed{
       id = 1102,
		 lv = 6,
		 name = <<"攻击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 30,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 600,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"攻击"/utf8>>
	}};
get(1102,7)->
	{ok,#data_skill_ed{
       id = 1102,
		 lv = 7,
		 name = <<"攻击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 35,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 700,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"攻击"/utf8>>
	}};
get(1102,8)->
	{ok,#data_skill_ed{
       id = 1102,
		 lv = 8,
		 name = <<"攻击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 40,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 800,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"攻击"/utf8>>
	}};
get(1102,9)->
	{ok,#data_skill_ed{
       id = 1102,
		 lv = 9,
		 name = <<"攻击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 45,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 900,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"攻击"/utf8>>
	}};
get(1102,10)->
	{ok,#data_skill_ed{
       id = 1102,
		 lv = 10,
		 name = <<"攻击"/utf8>>,
		 type = 1,
		 up_need_goods = [],
		 up_need_ll = 0,
		 need_country = 0,
		 need_job = 1,
		 need_lv = 50,
		cd = 0,
		hp = 0,
		mp = 0,
		att = 1000,
		def = 0,
		hit = 0,
		duck = 0,
		crit = 0,
		ten = 0,
		rhurt = 0,
		phurt = 0,
		speed = 0,
		buff_ids = [],
		 transfer = [102,202,302],
		 explain = <<"攻击"/utf8>>
	}};
get(_Id,_Lv)->
	{error,no_match}.
